# Generated by Django 4.2.3 on 2023-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_delete_studentperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_examiner",
            field=models.BooleanField(default=False),
        ),
    ]
