# Generated by Django 4.2.3 on 2023-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_customuser_is_examiner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("unit_1_cat1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_1_cat2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_1_exam", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_2_cat1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_2_cat2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_2_exam", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_3_cat1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_3_cat2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_3_exam", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_4_cat1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_4_cat2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_4_exam", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
