# Generated by Django 4.2.3 on 2023-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_classlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classlist",
            name="unit_1_cat1",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_1_cat2",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_1_exam",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_2_cat1",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_2_cat2",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_2_exam",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_3_cat1",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_3_cat2",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_3_exam",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_4_cat1",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_4_cat2",
        ),
        migrations.RemoveField(
            model_name="classlist",
            name="unit_4_exam",
        ),
        migrations.AddField(
            model_name="classlist",
            name="course",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="classlist",
            name="id_number",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name="classlist",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="classlist",
            name="year_of_intake",
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
    ]
